#pragma once

typedef enum {
    COMPILE_OK,
    COMPILE_ERROR,
    PREPROCESS_ERROR,
    LEXICAL_ERROR,
    SYNTAX_ERROR,
    SEMANTICAL_ERROR,
    GENERATION_ERROR,
    OUT_OF_PATH,
    WRONG_PATH,
    MALLOC_ERROR,
    READFILE_ERROR,
    WRITEFILE_ERROR,
    EXPLODE_MAX_ERRORS,
} ExiCodes;
